GET http://localhost:8080/todos

###
POST http://localhost:8080/todos
Content-Type: application/json

{
    "id": 6,
    "name": "new todo!!!!"
}

###
GET http://localhost:8080/todos/2


###
DELETE http://localhost:8080/todos/6

